name = "nest-project"
main = "dist/main.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "modules"
main = "./dist/main.js"
dir = "dist"

[env.production]
workers_dev = true

[env.production.vars]
NODE_ENV = "production"
PORT = "8080"

[triggers]
crons = [] 